name: 'payy1-test'
on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: browser-actions/setup-chrome@latest
      - name: 'ðŸ–¼ Running Pa11y...'
        uses: ./
        with:
          port: '3000'
          start: 'app:start'